name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - "ubuntu-latest"
          - "macos-latest" 
          - "windows-latest"
        python-version:
        #   - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
        #   - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
                pwd
                ls -la
            elif [[ "$RUNNER_OS" == "Windows" ]]; then
              dir/w
            else
              echo "$RUNNER_OS not supported"
              exit 1
            fi
            
            cd github-actions-example-1
            python -m pip install pytest 


      - name: Run Tests
        run: pytest

        PsG0pOX55dQABxKIjMVgY